from .subcellular_localization import SubcellularLocalization
from .subcellular_localization_binary import SubcellularLocalizationBinary
from .gene_ontology import GeneOntology
from .metal_ion_binding import MetalIonBinding
from .scope_fold_rank import ScopeFoldRank